force-app/main/default/objects/BWP_Payment_Method__c/BWP_Payment_Method__c.object-meta.xml
<CustomObject>
    <label>BWP Payment Method</label>
    <nameField>
        <displayFormat>PMTH-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BWP Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BWP_Processor_Config__c/BWP_Processor_Config__c.object-meta.xml
<CustomObject>
    <label>BWP Processor Config</label>
    <nameField>
        <label>BWP Processor Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BWP Processor Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Access_Token_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Access_Token_Expiry_Date__c</fullName>
    <label>Access Token Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Card_Creation_Key__c.field-meta.xml
<CustomField>
    <fullName>Card_Creation_Key__c</fullName>
    <description>This field is used while card creation using JS.</description>
    <label>Card Creation Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Customer_Match_Config__c.field-meta.xml
<CustomField>
    <fullName>Customer_Match_Config__c</fullName>
    <description>Used to show the Customers in Account or Contact Match based on the configuration values stored.</description>
    <label>Customer Match Config</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Customer_Match_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Match_Type__c</fullName>
    <description>Used to store selected Customer Match Type (Account/Contact) value.</description>
    <label>Customer Match Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Customer_Sync_Config__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sync_Config__c</fullName>
    <description>Used to import the Customers into Salesforce, based on the configuration values stored.</description>
    <label>Customer Sync Config</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Default_Currency__c.field-meta.xml
<CustomField>
    <fullName>Default_Currency__c</fullName>
    <label>Default Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Historical_Customer_Sync_Last_Run__c.field-meta.xml
<CustomField>
    <fullName>Historical_Customer_Sync_Last_Run__c</fullName>
    <label>Historical Customer Sync Last Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Historical_Payment_Sync_Last_Run__c.field-meta.xml
<CustomField>
    <fullName>Historical_Payment_Sync_Last_Run__c</fullName>
    <label>Historical Payment Sync Last Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Hourly_Customer_Sync_Last_Run__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Customer_Sync_Last_Run__c</fullName>
    <label>Hourly Customer Sync Last Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Hourly_Payment_Sync_Last_Run__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Payment_Sync_Last_Run__c</fullName>
    <description>We are replacing Hourly words with Regular everywhere in the app.</description>
    <label>Regular Payment Sync Last Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Is_Customer_Match_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Customer_Match_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Customer Match Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Last_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Last_Customer_Id__c</fullName>
    <label>Last Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Live_Mode__c.field-meta.xml
<CustomField>
    <fullName>Live_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Live Mode</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Need_To_Reconnect__c.field-meta.xml
<CustomField>
    <fullName>Need_To_Reconnect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need To Reconnect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Payment_Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor_Type__c</fullName>
    <label>Payment Processor Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BWP_Processor_Config__c/fields/Provider_ID__c.field-meta.xml
<CustomField>
    <fullName>Provider_ID__c</fullName>
    <label>Provider ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Selector_BWP_ProcessorConfig.cls
@namespaceAccessible
public with sharing class Selector_BWP_ProcessorConfig extends QuerySelector {
    @namespaceAccessible
    public static List<Schema.SObjectField> FIELD_LIST {
        get {
            if (FIELD_LIST == null) {
                // We are getting a strange QueryBuilder : Access Denied: DML_READ on the LastViewedDate
                // if we do this FIELD_LIST = BWP_Payment_Method__c.SObjectType.getDescribe().fields.getMap().values();
                // But only when it's installed as a package
                // Instead of wasting more time I decide to just hardcode the list
                FIELD_LIST = new List<Schema.SObjectField>{
                    BWP_Processor_Config__c.Id,
                    BWP_Processor_Config__c.Name,
                    BWP_Processor_Config__c.Access_Token__c,
                    BWP_Processor_Config__c.Refresh_Token__c,
                    BWP_Processor_Config__c.Access_Token_Expiry_Date__c,
                    BWP_Processor_Config__c.Account_Name__c,
                    BWP_Processor_Config__c.Card_Creation_Key__c,
                    BWP_Processor_Config__c.Customer_Match_Config__c,
                    BWP_Processor_Config__c.Customer_Match_Type__c,
                    BWP_Processor_Config__c.Customer_Sync_Config__c,
                    BWP_Processor_Config__c.Default_Currency__c,
                    BWP_Processor_Config__c.End_Date__c,
                    BWP_Processor_Config__c.Historical_Customer_Sync_Last_Run__c,
                    BWP_Processor_Config__c.Historical_Payment_Sync_Last_Run__c,
                    BWP_Processor_Config__c.Hourly_Customer_Sync_Last_Run__c,
                    BWP_Processor_Config__c.Hourly_Payment_Sync_Last_Run__c,
                    BWP_Processor_Config__c.Is_Customer_Match_Completed__c,
                    BWP_Processor_Config__c.Last_Customer_Id__c,
                    BWP_Processor_Config__c.Live_Mode__c,
                    BWP_Processor_Config__c.Need_To_Reconnect__c,
                    BWP_Processor_Config__c.Payment_Processor_Type__c,
                    BWP_Processor_Config__c.Provider_ID__c,
                    BWP_Processor_Config__c.Scope__c,
                    BWP_Processor_Config__c.Start_Date__c
                };
            }
            return FIELD_LIST;
        }
        private set;
    }

    @namespaceAccessible
    public Selector_BWP_ProcessorConfig() {
        super();
    }

    @namespaceAccessible
    public override Schema.SObjectType getSObjectType() {
        return BWP_Processor_Config__c.SObjectType;
    }
    
    private List<Schema.SObjectField> sObjectFieldList;
    @namespaceAccessible
    public override List<Schema.SObjectField> getSObjectFieldList() {
        return sObjectFieldList != null ? sObjectFieldList : FIELD_LIST;
    }
    /**
    * Allows the calling class to override the default FIELD_LIST
    * @param fieldList list of field that will be passed into the query
    */
    @namespaceAccessible
    public void setSObjectFieldList(List<Schema.SObjectField> fieldList){
        this.sObjectFieldList = fieldList;
    }
    
    private String orderBy;
    @namespaceAccessible
    public override String getOrderBy() {
        return String.isBlank(orderBy) ? 'DeveloperName ASC' : orderBy;
    }
    
    @namespaceAccessible
    public List<BWP_Processor_Config__c> getAllAppConfig(){
        QueryBuilder qb = newQueryBuilder();
        return (List<BWP_Processor_Config__c>) Database.query(qb.toSOQL());
    }
    
    @namespaceAccessible
    public List<BWP_Processor_Config__c> selectByProcessorId(Set<String> idSet){
        QueryBuilder qb = newQueryBuilder();
        qb.setCondition('Provider_ID__c IN :idSet');
        return (List<BWP_Processor_Config__c>) Database.query(qb.toSOQL());
    }
    
}